name: Checkout Repository
description: Clone a Repository
inputs:
  url:
    description: 'Repository URL to Clone'
    required: false
    default: ${{ gitea.repository }}
  dir:
    description: 'Directory to Clone Into'
    required: false
    default: '.'
  token:
    description: 'Authentication Token'
    required: false
  branch:
    description: 'Branch to Clone'
    required: false

runs:
  using: composite
  steps:
    - name: Cloning Repository
      shell: bash
      run: |
        set -e
        
        URL="${{ inputs.url }}"
        echo $URL
        DIR="${{ inputs.dir }}"
        TOKEN="${{ inputs.token }}"
        BRANCH="${{ inputs.branch }}"
        
        if [[ -z "$URL" ]]; then
          echo "Error: url parameter is required"
          exit 1
        fi
        
        if [[ -z "$DIR" ]]; then
          DIR="."
        fi
        
        CLONE_CMD="git clone"
        
        if [[ -n "$BRANCH" ]]; then
          CLONE_CMD="$CLONE_CMD --branch $BRANCH"
        fi
        
        if [[ -n "$TOKEN" ]]; then
          CLONE_CMD="$CLONE_CMD https://${TOKEN}@${URL}"
        else
          CLONE_CMD="$CLONE_CMD $URL"
        fi
        
        CLONE_CMD="$CLONE_CMD $DIR"
        
        echo "Cloning repository..."
        echo "Command: $CLONE_CMD"
        
        eval $CLONE_CMD
        
        echo "Repository cloned successfully to: $DIR"
