name: Checkout Repository
description: Clone a Repository
inputs:
  url:
    description: 'Repository URL to Clone'
    required: true
  dir:
    description: 'Directory to Clone Into'
    required: false
    default: '.'
  ssh_key:
    description: 'SSH Private Key for authentication'
    required: true
  branch:
    description: 'Branch to Clone'
    required: false

runs:
  using: composite
  steps:
    - name: Cloning Repository
      shell: bash
      run: |
        set -e
        
        URL="${{ inputs.url }}"
        DIR="${{ inputs.dir }}"
        SSH_KEY="${{ inputs.ssh_key }}"
        BRANCH="${{ inputs.branch }}"
        
        if [[ -z "$URL" ]]; then
          echo "Error: url parameter is required"
          exit 1
        fi
        
        if [[ -z "$DIR" ]]; then
          DIR="."
        fi
        
        CLONE_CMD="git clone"
        
        if [[ -n "$BRANCH" ]]; then
          CLONE_CMD="$CLONE_CMD --branch $BRANCH"
        fi
        
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        echo "StrictHostKeyChecking=no" >> ~/.ssh/config
        
        CLONE_CMD="$CLONE_CMD $URL"
        
        CLONE_CMD="$CLONE_CMD $DIR"
        
        echo "Cloning repository..."
        echo "Command: $CLONE_CMD"
        
        eval $CLONE_CMD
        
        echo "Repository cloned successfully to: $DIR"
